### ISSUE TITLE
Incompatibility with python 3.0 due to rename of configparser module.

### ISSUE THREAD

**Issue by brettc** [trek10inc/awsume#10]
See here: https://docs.python.org/2/library/configparser.html

**Comment by veqryn** [comment]
```MinGW 03:24:54 ~/workspace/go/src/github.com/ReturnPath/terraform-templates/rp-eo/ecr$ pip3 install ConfigParser
Collecting ConfigParser
  Downloading configparser-3.5.0.tar.gz
Installing collected packages: ConfigParser
  Running setup.py install for ConfigParser: started
    Running setup.py install for ConfigParser: finished with status 'done'
Successfully installed ConfigParser-3.5.0
MinGW 03:25:13 ~/workspace/go/src/github.com/ReturnPath/terraform-templates/rp-eo/ecr$
MinGW 03:25:17 ~/workspace/go/src/github.com/ReturnPath/terraform-templates/rp-eo/ecr$ `awsume -s eo`
Traceback (most recent call last):
  File "C:\Program Files\Python3\Scripts\awsumepy-script.py", line 11, in <module>
    load_entry_point('awsume==1.2.1', 'console_scripts', 'awsumepy')()
  File "c:\program files\python3\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\program files\python3\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\program files\python3\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\program files\python3\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\program files\python3\lib\site-packages\awsume\awsumepy.py", line 3, in <module>
    import ConfigParser, re, argparse, collections, datetime, dateutil, boto3, psutil, logging
ModuleNotFoundError: No module named 'ConfigParser'
```

**Comment by mbarneyjr** [comment]
I believe I solved the Python3 compatibility issues. You may update AWSume to version 1.2.2 now. Thank you!
