### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by GersonRosales** [trek10inc/awsume#207]
I'm getting this error after install and make the configuration 

```
bash-3.2$ awsume
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/awsumepy", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/awsume/awsumepy/main.py", line 29, in main
    run_awsume(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/awsume/awsumepy/main.py", line 16, in run_awsume
    awsume = app.Awsume()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/awsume/awsumepy/app.py", line 33, in __init__
    self.config['is_interactive'] = is_interactive
TypeError: list indices must be integers or slices, not str
```

This is the versions I'm using
```
awsume                   4.5.3
Python 3.10.6
```

**Comment by GersonRosales** [comment]
it worked! thanks!!
