### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by blastik** [trek10inc/awsume#240]
In the latest brew release `4.5.3_3` i get the following error

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/awsumepy", line 5, in <module>
    from awsume.awsumepy.main import main
  File "/opt/homebrew/Cellar/awsume/4.5.3_3/libexec/lib/python3.12/site-packages/awsume/awsumepy/__init__.py", line 1, in <module>
    from . import app
  File "/opt/homebrew/Cellar/awsume/4.5.3_3/libexec/lib/python3.12/site-packages/awsume/awsumepy/app.py", line 12, in <module>
    from . lib.autoawsume import create_autoawsume_profile
  File "/opt/homebrew/Cellar/awsume/4.5.3_3/libexec/lib/python3.12/site-packages/awsume/awsumepy/lib/__init__.py", line 1, in <module>
    from . import aws_files
  File "/opt/homebrew/Cellar/awsume/4.5.3_3/libexec/lib/python3.12/site-packages/awsume/awsumepy/lib/aws_files.py", line 9, in <module>
    from . safe_print import safe_print
  File "/opt/homebrew/Cellar/awsume/4.5.3_3/libexec/lib/python3.12/site-packages/awsume/awsumepy/lib/safe_print.py", line 5, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by blastik** [comment]
https://github.com/Homebrew/homebrew-core/issues/151641#issuecomment-1768620529
