### ISSUE TITLE
awsume development on python 3.12

### ISSUE THREAD

**Issue by cspotcode** [trek10inc/awsume#264]
Is there a developer guide to clone, develop, and run tests for awsume?

On python 3.12, `pip install pipenv` and then `pipenv` gives an error traceback about `module 'collections' has no attribute 'MutableMapping'`:

```
❯ pipenv
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 33, in <module>
    sys.exit(load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')())
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1018, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 875, in parse_args
    parser = self.make_parser(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 821, in make_parser
    for param in self.get_params(ctx):
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 774, in get_params
    help_option = self.get_help_option(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 26, in get_help_option
    from .import core
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 21, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/__init__.py", line 65, in <module>
    from . import utils
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

Python isn't my main development environment, so I'd rather not go down a rabbit hole learning all the intricacies and gotchas of python's venv / dependency management landscape.  Is there a quick guide to setting up a dev environment for awsume?

**Comment by cspotcode** [comment]
I see the test matrix doesn't run on anything newer than python 3.9; is that related?

https://github.com/trek10inc/awsume/blob/ea212bf8c55a3b8fe290c20817c5d90c52bc9d8c/.github/workflows/test.yml#L17

**Comment by cspotcode** [comment]
Thanks for taking a look.  I don't think I'll be able to find it, I somehow
got it to build and don't remember exactly how.  Then I made a static
binary with Nuitka so I wouldn't have to repeat on other machines; could
just copy the binary.

Not your fault, but I really dislike *every* time I have to install any
python tool, it feels like the python ecosystem has dozens of version and
dependency managers and my coworkers and I *invariably* hit problems with
installation.

The static binary is working great so far, awsume itself is doing the
trick.  Thanks!

**Comment by mtskillman** [comment]
per above comments, considering issue as resolved
