### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] when using awsume on WSL with Zscaler

### ISSUE THREAD

**Issue by rfruit17** [trek10inc/awsume#266]
Awsume version: 4.5.4
Installation method: pipx
AWS CLI version: 2.17.12 
OS: WSL (on Windows)
Firewall/VPN: Zscaler

Whenever I try to execute command `awsume my_profile` I get error: `Awsume error: SSL validation failed for https://sts.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)`

Surprisingly, when using AWS CLI everything works fine: `aws s3 ls --profile my_profile` does not raise any error. Because of Zscaler, I had to explicitly add file `/usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt` and run `sudo update-ca-certificates -f`(before that AWS CLI was not working either).

I tried to reinstall awsume but the problem persists. Is there anyway to check which certificates awsume is using ?
I suspected that the problem could be because of botocore but when I execute `/home/my_user/.local/pipx/venvs/awsume/bin/python -c "from botocore.session import Session; print(Session().get_config_variable('ca_bundle'))"` the outcome is  `/usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt` which seems fine.

I am also facing a [similar issue](https://github.com/benkehoe/aws-sso-util/issues/123) with aws-sso-util.

Here is the detailed Traceback:

```
Traceback (most recent call last):
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
                      ^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/urllib3/util/retry.py", line 449, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/awsume/awsumepy/lib/aws.py", line 66, in assume_role
    role_session = role_sts_client.assume_role(**kwargs).get('Credentials')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/client.py", line 1001, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/client.py", line 1027, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
          ^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
                   ^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
                       ^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/botocore/httpsession.py", line 491, in send
    raise SSLError(endpoint_url=request.url, error=e)
botocore.exceptions.SSLError: SSL validation failed for https://sts.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/awsume/awsumepy/app.py", line 265, in run
    credentials = self.get_credentials(args, profiles)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/awsume/awsumepy/app.py", line 204, in get_credentials
    credentials = self.plugin_manager.hook.get_credentials(config=self.config, arguments=args, profiles=profiles)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/awsume/awsumepy/default_plugins.py", line 626, in get_credentials
    credentials = get_credentials_handler(config=config, arguments=arguments, profiles=profiles, profile_name=profile_name, credentials=credentials)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/awsume/awsumepy/default_plugins.py", line 596, in get_credentials_handler
    role_session = get_assume_role_credentials(config, arguments, profiles, target_profile, role_duration, credentials, profile_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/awsume/awsumepy/default_plugins.py", line 411, in get_assume_role_credentials
    role_session = aws_lib.assume_role(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/awsume/lib/python3.11/site-packages/awsume/awsumepy/lib/aws.py", line 71, in assume_role
    raise RoleAuthenticationError(str(e))
awsume.awsumepy.lib.exceptions.RoleAuthenticationError: SSL validation failed for https://sts.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)
Awsume error: SSL validation failed for https://sts.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)
```

**Comment by rfruit17** [comment]
I have solved my own problem.
The parameter `default.ca_bundle` was set in `~/.aws/config`:

```

[default]
ca_bundle = /usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt

```
The path is correct and yet it was causing an SSL error with `awsume` and `aws-sso-util`.
For some reasons, this does not cause any issue with AWS CLI.

**Comment by rfruit17** [comment]
I have solved my own problem.
The parameter `default.ca_bundle` was set in `~/.aws/config`:

```

[default]
ca_bundle = /usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt

```
The path is correct and yet it was causing an SSL error with `awsume` and `aws-sso-util`.
For some reasons, this does not cause any issue with AWS CLI.
