### ISSUE TITLE
KeyError: 'expiration' when passing `--auto-refresh` with profile

### ISSUE THREAD

**Issue by JoshC-Innovative** [trek10inc/awsume#275]
when passing the `-a` or `--auto-refresh` after a `. assume my-profile` I receive the following Error key...

I'm using the latest version from a pipx install

```
awsume is already at latest version 4.5.4 (location: /Users/jcrosby/.local/pipx/venvs/awsume)

11:27 $
. awsume my-profile -a
[my-profile] Role credentials will expire 2024-09-11 12:27:42
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/autoawsume", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/awsume/autoawsume/main.py", line 38, in main
    expiration = datetime.strptime(auto_profile['expiration'], '%Y-%m-%d %H:%M:%S')
                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'expiration'
```

**Comment by alexma01** [comment]
same here
