### ISSUE TITLE
awsume --list throws error

### ISSUE THREAD

**Issue by shortjared** [trek10inc/awsume#36]
```
$ awsume -l
Traceback (most recent call last):
  File "/usr/local/bin/awsumepy", line 11, in <module>
    load_entry_point('awsume==3.2.8', 'console_scripts', 'awsumepy')()
  File "/usr/local/lib/python2.7/site-packages/awsume/awsumepy.py", line 1668, in main
    awsume.run(command_line_arguments)
  File "/usr/local/lib/python2.7/site-packages/awsume/awsumepy.py", line 1632, in run
    mix_role_and_source_profiles(profiles)
  File "/usr/local/lib/python2.7/site-packages/awsume/awsumepy.py", line 284, in mix_role_and_source_profiles
    merge_role_and_source_profile(profiles[profile], profiles[source_profile_name])
  File "/usr/local/lib/python2.7/site-packages/awsume/awsumepy.py", line 259, in merge_role_and_source_profile
    role_profile['aws_access_key_id'] = source_profile['aws_access_key_id']
KeyError: 'aws_access_key_id'
```

everything else works just fine. super weird.

**Comment by mbarneyjr** [comment]
Discussed behind the scenes

**Comment by esn89** [comment]
I am having a same error here when I try to awsume <role> how did you guys fix this?

**Comment by varun1231** [comment]
@mbarneyjr what was the fix here? We are struggling with this on one of the boxes.
