### ISSUE TITLE
Autoawsume throws during credential refresh

### ISSUE THREAD

**Issue by c-bandy** [trek10inc/awsume#69]
In 4.1.6 refreshing fails with the following error trace

```
Traceback (most recent call last):
  File "/usr/local/bin/autoawsume", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/awsume/autoawsume/main.py", line 32, in main
    session = awsumepy.awsume(*auto_profile.get('awsumepy_command').split(' '))
  File "/usr/local/lib/python3.7/site-packages/awsume/awsumepy/awsume.py", line 16, in awsume
    return app.run([profile_name] + cli_arguments)
  File "/usr/local/lib/python3.7/site-packages/awsume/awsumepy/app.py", line 247, in run
    credentials = self.get_credentials(args, profiles)
  File "/usr/local/lib/python3.7/site-packages/awsume/awsumepy/app.py", line 186, in get_credentials
    credentials = json.loads(json_input)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mbarneyjr** [comment]
From the traceback, it looks like you're supplying `args.json` or credentials are being piped into awsume like this:

```
echo "{...credentials}" | awsume
# or
awsume --json '{...credentials}'
```

which tells awsume to export those credentials. This functionality is not supported for autoawsume since it cannot regenerate the credentials you're passing to it

If this is not how you're using awsume, could you provide the commands you're using? Also any details about your environment (like OS, shell, etc)?

**Comment by c-bandy** [comment]
I'm just using `awsume profilename --auto-refresh`. When it's close to expiration that error throws.

`~/.aws/config`:

```
[profile profilename]
role_arn = arn:aws:iam::xxxxxxxxx:role/xxxxxxxxx
mfa_serial = arn:aws:iam::xxxxxxxxx:mfa/xxxxxxxxx
source_profile = root
region = eu-west-1
```

`~/.aws/credentials`:

```
[root]
aws_access_key_id = xxxxxxxx
aws_secret_access_key = xxxxxxxx
```

I'm on macOs Catalina Beta, using the fish shell. :fish:

**Comment by mbarneyjr** [comment]
Hmm, if you autorefresh a profile again, what is the contents of your `autoawsume-profilename` profile in the credentials profile (redacted of course)?

**Comment by c-bandy** [comment]
```
[autoawsume-profilename]
aws_access_key_id = xxxxxxxxx
aws_secret_access_key = xxxxxxxxx
aws_session_token = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
region = eu-west-1
expiration = 2019-10-01 21:19:15
source_expiration = 2019-10-02 08:19:14
awsumepy_command = profilename -a
```

**Comment by c-bandy** [comment]
Oh, you mean _after_ it tries to refresh. Give me an hour 🙂

**Comment by c-bandy** [comment]
I got the error again, and the `credentials` didn't update actually. I guess it crashes before anything is written.

**Comment by mbarneyjr** [comment]
Alrighty, this _should_ be fixed in 4.1.7.

For some reason in some successive calls to awsume, `sys.stdin.isatty()` was returning False, which is what is used to check for data being piped into awsume from stdin.

I'm going to leave this issue open until you confirm it works for you, feel free to leave a comment or close if it works, thanks!

**Comment by c-bandy** [comment]
Argh, I still have issues in 4.1.7

```
Traceback (most recent call last):
  File "/usr/local/bin/autoawsume", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/awsume/autoawsume/main.py", line 32, in main
    session = refresh_profile(auto_profile)
  File "/usr/local/lib/python3.7/site-packages/awsume/awsumepy/awsume.py", line 16, in awsume
    return app.run([profile_name] + cli_arguments)
  File "/usr/local/lib/python3.7/site-packages/awsume/awsumepy/app.py", line 247, in run
    credentials = self.get_credentials(args, profiles)
  File "/usr/local/lib/python3.7/site-packages/awsume/awsumepy/app.py", line 186, in get_credentials
    credentials = json.loads(json_input)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by mbarneyjr** [comment]
I pushed an update (4.1.8), which should hopefully resolve this issue

**Comment by c-bandy** [comment]
It looks like you accidentally [killed the fish](https://github.com/trek10inc/awsume/commit/7c657383948d5220bfa16f925afe27dae90a4e60#diff-65a057d035216cb38a6b94dcf6a0b126), might want to fix that

**Comment by mbarneyjr** [comment]
So the fish script wasn't actually up-to-date (and wasn't functional), and it wasn't being used. The `awsume` script is what was being called when `awsume` is ran. It should not be necessary even if fish is being used as the default shell

**Comment by c-bandy** [comment]
Gotcha, can install now at least. I'll close this when I can confirm that it works
