### ISSUE TITLE
Date comparison error

### ISSUE THREAD

**Issue by alexbilbie** [trek10inc/awsume#70]
I've just updated to the latest awsume available on pip (4.1.6) and I'm seeing this error:

```
$ awsume platform-production-admin -a
Session token will expire at 2019-10-01 22:38:18
Role credentials will expire 2019-10-01 16:07:34
[3] 52308

Traceback (most recent call last):
  File "/usr/local/bin/autoawsume", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/awsume/autoawsume/main.py", line 41, in main
    earliest_expiration = min(expirations)
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by mbarneyjr** [comment]
This should be fixed in 4.1.7, thanks for the bug report!
